num_data <- data %>% select(where(is.numeric), -student_id)
corr_matrix <- cor(num_data, use = "complete.obs")
corrplot(corr_matrix, method = "color", type = "lower")
corrplot(corr_matrix, method = "color", type = "lower", p.mat = cor.mtest(num_data)$p, sig.level = 0.05)
corrplot(corr_matrix, method = "color", type = "lower", order = "hclust")
corrplot(corr_matrix, col = colorRampPalette(c("red", "white", "blue"))(100))
